# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  box_url  = "https://s3.amazonaws.com/easybibdeployment/easybib-ubuntu-14.04.1_vbox-4.3.12_chef-11.10.4_0.1.box"
  box_file = "easybib-ubuntu-14.04.1_vbox-4.3.12_chef-11.10.4_0.1"

  config.vm.box      = box_file
  config.vm.box_url  = box_url
  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui
  
  vagrant_boxname    = "Package Builder Box"
  vagrant_memorysize = "1024"

  config.vm.provider :virtualbox do |vb|
     vb.gui = false
     vb.customize [
             "modifyvm", :id,
             "--name",   vagrant_boxname,
             "--memory", vagrant_memorysize
     ]
  end

  config.vm.provision :shell, :path => "./scripts/setup.sh"
  config.vm.synced_folder "./../", "/packaging", :owner => "vagrant", :nfs => false
  
end
